logging:
  config: classpath:logback-spring.xml
  file:
    max-size: 500MB
    max-history: 30
    path: /data/logs/${spring.application.name}
    total-size-cap: 20GB
  level:
    root: info

# 配置sql打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

spring:
  application:
    name: template
  profiles:
    active: dev

